- src/common/utils.ts
- src/content/translate.ts
由于OpenAI免费帐号限制，用多个API Key，可以作为一个资源池，随机挑选一个API Key使用。
> 支持多API Key，用分号`;`隔开

- src/content_script/index.tsx
> It is worth noting that currently getSelection() doesn't work on the content of textarea  and input elements in Firefox and Edge (Legacy)
ref: https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection#related_objects
> fix(firefox): getSelection not work on input and textarea elements

- .prettierrc.js
- public/manifest.firefox.json
- public/manifest.json
remove the parser option to avoid Prettier raising an error while formatting the JSON file.
> fix: remove prettier parser option

- build.mjs
Currently, there is no need to use the `deleteOldDir` function since we run `ramrif` before the build process.
> chore: delete unnecessary code and formatting build.mjs

- public/manifest.firefox.json
> fix(firefox): correct permissions to remove warning

- src-tauri/tauri.conf.json
看到大佬居然借鉴了我的代码，好激动😆
但是有点小问题，这里的xdotool一般各大发行版都不会预装，需要加到依赖里边。
```rust
#[cfg(target_os = "linux")]
fn get_mouse_location() -> Result<(i32, i32), String> {
use std::process::Command;
let output: String = match Command::new("xdotool").arg("getmouselocation").output() {
Ok(v) => String::from_utf8(v.stdout).unwrap(),
Err(e) => return Err(format!("xsel failed: {}", e.to_string())),
};
let output: Vec<&str> = output.split_whitespace().collect();
let x = output
.get(0)
.unwrap()
.replace("x:", "")
.parse::<i32>()
.unwrap();
let y = output
.get(1)
.unwrap()
.replace("y:", "")
.parse::<i32>()
.unwrap();
return Ok((x, y));
}
```
> fix: fix missing linux dependences

- .github/workflows/release.yaml
- .github/workflows/test-build.yaml
- src-tauri/src/utils.rs
Right now the github action only output x64 (Intel chip) build for MacOS. This PR should allow the action to release a universal build.
Also added a workflow to trigger manual build for testing.
> fix: macos universal build

- src-tauri/src/windows.rs
1. Bug: clicking the **minimize icon** of the window, shortcut keys cannot bring up the window again.
2. Click **the blank part** to minimize not affected the shortcut keys.
It's seems the operator 1 is minimize the window, but operator 2 is hide.
I try `window.unminimize()` when call `show_main_window()`, it's fixed.
The last, thank you for your interesting creation😊.
> fix: when window minimized, shortcut key invalid

- src/content_script/PopupCard.tsx
Adjust the `placement` of `<StatefulTooltip />` depending on `isDesktopApp()`.
By the way, should we consider making the userscript an artifact in releases rather than tracking it in the git history?
> fix: tooltip position on desktop (resolves #193)

- src/tauri/App.tsx
Because the system tray is already supported, modify the behavior of the close button : hide the window instead of closing it.
I found that calling **window. close()** will not trigger the **CloseRequested** event.
So this code only works when the native close button is used. 
Windows and Linux have used **window.set_decorations (false)** hides the native close button.
https://github.com/yetone/openai-translator/blob/d841aec397bce21ee55e3c193177e8268bf6a90c/src-tauri/src/main.rs#L72-L76
> hide the window instead of closing it

- src/background/index.ts
- src/content_script/index.tsx
Implementing support for pdf through contextmenu, only works in chrome, because firefox seems does not support running content scripts on pdf pages.(https://bugzilla.mozilla.org/show_bug.cgi?id=1454760)
However, there are some positioning issues because mouse events cannot be triggered on a pdf pages.
> feat: add pdf support to chrome using contextmenu

- .github/workflows/winget.yml
- README-CN.md
- README.md
Through the [PR](https://github.com/microsoft/winget-pkgs/pull/99321),  OpenAI Translator has been added to Winget. Windows users can now install it by executing the following command:
```sh
winget install yetone.OpenAITranslator
```
To better support Winget, we can integrate it into GitHub Actions. After that, once a new version is released, CI will automatically update that to Winget. Before merging this PR, please follow these steps:
1. Please add a GitHub token with public_repo and workflow scopes as a repository secret and rename the secret name to "WINGET_TOKEN" in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @yetone 
See [more info](https://github.com/vedantmgoyal2009/winget-releaser) about winget action.
> Support installing OpenAITranslator from winget

- src/content_script/lang.ts
Using the dataset from [Tatoeba](https://tatoeba.org/eng/downloads), approximately 10 million sentences in various languages were tested for accuracy using [languagedetect](https://www.npmjs.com/package/languagedetect) and [guesslanguage-ng](https://github.com/yetone/guessLanguage.ts). The overall results were disappointing. Overall, languagedetect performed slightly better than guesslanguage-ng, but languagedetect does not support East Asian languages, so the results of guesslanguage-ng are preferred for Japanese and Korean.
> Improve the accuracy of detecting Korean and Japanese

- src/tauri/App.tsx
- src/tauri/index.html
There seems no way to use the `:hover` pseudo selector in inline CSS, so I use `@media (prefers-color-scheme: dark)` for hover effect.
> fix: color of `titlebar-button` in dark mode

- .github/workflows/lint.yaml
Bump the `typos` in CI lint to >= [v1.13.23](https://github.com/crate-ci/typos/releases/tag/v1.13.23) to avoid Docker builds.
Result: https://github.com/WaterLemons2k/openai-translator/actions/runs/4434204025/jobs/7779963871
> chore(ci): bump `typos` to v1.13.24

- src/common/hooks/useThemeDetector.ts
按照 [这里](https://mobile.twitter.com/EmmerichBret/status/1507634652680540164/photo/1) 所提示的，在老版本的macos 不支持 给`prefers-color-scheme` 添加 `addEventListener`。
不过目前没有找到可供测试的（big sur，Catalina）系统。如果是这个的问题，那么这个补丁应该可以修复。
希望有老系统的可以测试下。
编译过的测试版本 [OpenAI Translator.app.zip](https://github.com/yetone/openai-translator/files/10999127/OpenAI.Translator.app.zip)
下面是测试用的patch，可以使 tauri 打开devtools。
```
diff --git a/src-tauri/Cargo.toml b/src-tauri/Cargo.toml
index 6bd5181..7c3b3ea 100644
--- a/src-tauri/Cargo.toml
+++ b/src-tauri/Cargo.toml
@@ -17,7 +17,7 @@ tauri-build = { version = "1.2.1", features = [] }
[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
-tauri = { version = "1.2.4", features = ["clipboard-all", "dialog-message", "fs-read-dir", "fs-read-file", …
```
> fix: old MacOS tauri app blank screen

- build.mjs
- public/manifest.firefox.json
- public/manifest.json
- public/userscript.js
看到使用了inline-import插件，所以在浏览器环境可以移除content_script.css插入到内容页面，防止可能出现的样式覆盖。
Seeing the use of the "inline-import" plugin, it is possible to remove the insertion of content_script.css into the content page in the browser environment to prevent potential style overrides.
> Remove the insertion of "content_script.css" from the content page.

- src/content_script/PopupCard.tsx
The explain code button is not fully displayed on extension popup card
> fix: explain code button is not fully displayed

- src/content_script/PopupCard.tsx
When users hit Enter while typing, it directly triggers translation, resulting in a poor experience for entering English text in spelling mode.
当用户拼写时敲击回车会直接触发翻译，使得在拼写模式下输入英文体验很不好。
- 修复前
- 修复后
> 🐛 fix: prevent from submisson when hitting Enter in composition

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src-tauri/src/ocr.rs
- src-tauri/src/tray.rs
- src-tauri/src/windows.rs
hi~ ~ this pr remove unsafe code, static mut in rust that may violate Rust memory security principles. 
making code more secure by using AtomicBool and Mutex to replace the same implementation. thanks~
> opt rust code, remove unsafe static mut by using AtomicBool and Mutex

- src/common/hooks/useMemoWindow.ts
Most configuration of appwindow is asynchronous,it is a pity I did ignore this before.Maybe it result in some ambiguous problems,and I guess the issue [#403](https://github.com/yetone/openai-translator/issues/403) may have something to do with this.
> optimize: the window configuration is asynchronous

- src/content_script/index.tsx
fixed the problem of repeatedly creating contextmenu in iframe page. 
[Here](https://github.com/yetone/openai-translator/discussions/342)
> fix: repeatedly create contextmenu in iframe pages

- .gitignore
- src/popup/Settings.tsx
Before:
After:
<table>
<tr>
<td><img width="452" alt="SCR-20230323-smq" src="https://user-images.githubusercontent.com/76864176/227206048-61f3cae7-14ac-413b-a191-3ea108606928.png">
</td>
<td>
</td>
</tr>
</table>
> fix(theme): hotkey settings color with dark mode

- public/popup.html
cld-min.js is not import when entering from the toolbar
> fix: import cld-min.js

- src/common/background-fetch.ts
Make the behavior of `readText()` consistent with `fetch`.
> fix: read full text

- src-tauri/src/main.rs
After closing and then clicking the icon in the dock, the window will be redisplayed
> feat(osx): Redisplay widnow by clicking the icon in the dock

- src/content_script/PopupCard.tsx
`Sentry.init` causes Firefox to crash.
----
After this, still doesn't work on Firefox due to `dexie`.
> fix: disable sentry on firefox

- src/browser-extension/options/index.css
- src/browser-extension/options/index.tsx
- src/common/components/Settings.tsx
Signed-off-by: Frost Ming <me@frostming.com>
This PR fixes the banner width overflow in the Options view and Popup view.
| Before | After |
| --- | --- |
| <img width="422" alt="image" src="https://github.com/openai-translator/openai-translator/assets/16336606/957001fa-ec1d-4288-972d-5e2b6c3e31ff"> | <img width="402" alt="image" src="https://github.com/openai-translator/openai-translator/assets/16336606/38ef55cd-ff17-4e1b-84f7-53f2452a6857"> |
> fix: banner overflow in the options view

- src/common/components/IpLocationNotification.tsx
- src/common/components/Translator.tsx
- src/common/i18n/locales/en/translation.json
- src/common/i18n/locales/zh-Hans/translation.json
- src/common/i18n/locales/zh-Hant/translation.json
- src/common/utils.ts
- src/tauri/thumb.tsx
Do not show IP location warning if not using official API Endpoint or ChatGPT. Also, added refreshing when settings changed.
> fix: IP warning when not using official API & draggable thumb (fixes #544, #715)

- src/common/polyfills/userscript.ts
compatible with more userscript managers, tested on [violentmonkey](https://github.com/violentmonkey/violentmonkey) and [userscripts](https://github.com/quoid/userscripts).
works on safari now by using userscripts.
> feat(userscript): support non-stream response

- clip-extensions/snipdo/openai-translator.ps1
不加参数curl请求可以正常发送，但是在Win 10 下会报无法解析返回的错误。
> fix: Fix SnipDo  Command Error

- README-CN.md
- README.md
Azure OpenAI Service chat is GA now.
https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/whats-new#azure-openai-chat-completion-general-availability-ga
> pump the version of azure openai service to 2023-05-15 GA in README

- package.json
- pnpm-lock.yaml
Fixes #778 
This is caused by react-syntax-highlighter using refractor v3 https://github.com/wooorm/refractor/issues/59 Prism is a singletone, So It affect all site use Prism
The original repo of react-syntax-highlighter has not been updated for a long time so I publish my own package to fix the problem. https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/521
> fix: code highlight

- package.json
- pnpm-lock.yaml
- src/common/components/GlobalSuspense.tsx
- src/common/components/Settings.tsx
- src/common/components/Translator.tsx
- src/common/hooks/useCurrentThemeType.ts
- src/common/hooks/useSettings.ts
- src/common/hooks/useTheme.ts
- src/common/hooks/useThemeDetector.ts
- src/common/hooks/useThemeType.ts
Fixes: #761 and remove unnecessary setState
Since `getSettings` is async, I use swr to sync state between react and browser.storage. Use react suspense to prevent showing a init state.
As the asynchronous setting loading process is very fast, it feels like a dedicated loading fallback is not necessary. Currently, I have set the global loading fallback directly to blank.
> [Fix] 主题颜色初始化闪烁

- src/tauri/index.html
Adds css rule for `input` and `textarea` to fix input issues on macOS 12-. 
this is caused by setting `-webkit-user-select: none`.
related issues: https://github.com/openai-translator/openai-translator/issues/768, https://github.com/openai-translator/openai-translator/issues/767
reference:
1. https://github.com/tauri-apps/tauri/discussions/3541#discussioncomment-2570534
2. https://armno.in.th/blog/css-user-select/
> fix: unable to input on macOS 12-

- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .github/workflows/test-build.yaml
- .github/workflows/unit-test.yaml
- package.json
https://github.com/openai-translator/openai-translator/actions/runs/5140208408/jobs/9251451919?pr=797
``` 
ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
```
closes: #797
https://github.com/openai-translator/openai-translator/pull/797#issuecomment-1571312707
> ci: fix pnpm install errors

- src/common/translate.ts
- Added a new property 'history_and_training_disabled' to the translate function.
- Removed the unused 'conversationId' variable and related code.
- Removed the PATCH request to make the conversation invisible as it's no longer necessary.
> refactor: disable history and training in translate function

- src/common/lang/index.ts
之前的识别方法会因为大部分日语文章中都包含汉字而把日文识别为繁体中文
> fix: better language detecting

- src/common/translate.ts
如果返回的是这种错误
会因为试图把object直接插到react里而报错
修复后
> fix: showing error message

- src/common/components/Translator.tsx
- src/common/components/Vocabulary.tsx
why submit this PR?
I hope the sse handle logic be more compatible
I was writing a proxy adapter ( which proxy and emulate the openai api) to help people can use different backend (for example it can allow people use `Claude2`) in `openai-translator`. in the api, it emulate the response just like openai api.
all things works and `openai-translator` did not report any erorr. but I got the problem is, none of the translated results shown in the UI. it took me hours to debug this issue, finally I found the problem.
```javascript
if (message.role) {
return
}
```
the code just check if `message.role` not empty, then drop the result content.
this code assume that, when `message.role` present, the content must be empty.
I looks the official python client sdk, there's no such code.
and also I …
> should not depend on check role behavior, instead check the content

- .github/workflows/release.yaml
- src-tauri/tauri.conf.json
problem: linux appimage, click sound icon, no sound play
fix: including media framework on appimage to resolve audio not play issue
ref and thanks to: https://github.com/SlimeVR/SlimeVR-Server/pull/650
and as https://tauri.app/v1/guides/building/linux/#appimage
> CAUTION
> If your app plays audio/video you need to enable tauri.conf.json > tauri > bundle > appimage > bundleMediaFramework. This will increase the size of the AppImage bundle to include additional gstreamer files needed for media playback. This flag is currently only supported on Ubuntu build systems.
> fix: including media framework on appimage to resolve audio not play issue

- src/common/components/Settings.tsx
- src/common/components/Translator.tsx
- src/common/i18n/locales/en/translation.json
- src/common/i18n/locales/ja/translation.json
- src/common/i18n/locales/th/translation.json
- src/common/i18n/locales/zh-Hans/translation.json
- src/common/i18n/locales/zh-Hant/translation.json
- src/common/types.ts
- src/common/utils.ts
Add a new option, default state is off. 
After turning on, it will automatically read aloud the selected words:
> feat: read aloud the selected words from sentence in textarea automatically

- src/common/components/Settings.tsx
- src/common/token.ts
- src/common/translate.ts
Currently, 'openai-translator' does not support the select on the latest gpt-3.5 model "gpt-3.5-turbo-1106", see [this GPT-3.5 model list](https://platform.openai.com/docs/models/gpt-3-5) for more details.
Per my own experience on these gpt-3.5 models, "gpt-3.5-turbo-1106" outperform "gpt-3.5-turbo" on both speed and accuracy aspects. Hence I want to enable the choice of this model on settings page.
> chore: add latest gpt-3.5-turbo-1106 model option

- src/browser-extension/manifest.ts
部分网站使用了空网址 + srcdoc 的方式展示内容，该 PR 对该情形增加了兼容
> feat: support about:blank iframe

- src-tauri/src/main.rs
- src-tauri/src/ocr.rs
- src-tauri/src/windows.rs
- src-tauri/src/writing.rs
- src/tauri/utils.ts
https://tauri.app/v1/guides/features/multiwindow/
> fix: use async to create windows and avoid deadlock on Windows as the tauri document said

- README.md
Close #1061.
According to https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-35-models:
> GPT-3.5 Turbo is used with the Chat Completion API. GPT-3.5 Turbo version 0301 can also be used with the Completions API. GPT-3.5 Turbo versions 0613 and 1106 only support the Chat Completions API.
With the previous URL path:
After:
> README: update the Azure OpenAI API URL path

- README-CN.md
The Chinese version of this variable has not been updated. The new models can no longer use completions.
> fix API_URL_PATH in README-CN

- src/common/components/Translator.tsx
When using the Together api, an error is reported at the end of the response, but the content is output in its entirety. After debugging, I found that the Together response ends with `eos` instead of `stop`, which is a normal return. After modifying it, everything works fine.
> fix: Adjust the criterion for determining a normal end to streaming output.

- .github/workflows/release.yaml
Update release.yaml
fix macOS x86_64 version release #1501
[Standard GitHub-hosted runners for Public repositories](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
> fix: macOS x86_64 version release

- src/browser-extension/options/index.tsx
Background color does not extend beyond the viewport height in /src/browser-extension/options/index.html
> fix: fix background color issue where it did not extend beyond viewport

- src/tauri/utils.ts
- src/tauri/windows/SettingsWindow.tsx
- src/tauri/windows/TranslatorWindow.tsx
When modifying the settings through the "Settings" menu to access the settings page, the changes are saved but the hotkeys are not rebound. A restart is required for the hotkeys to take effect. 
This PR adds the 'onSave' function in the menu window to keep the functions of the two settings pages consistent.
> fix: fix the issue where hotkeys were not updated when saved in the settings window

- src-tauri/src/config.rs
- src-tauri/src/main.rs
- src-tauri/src/tray.rs
- src/common/hooks/usePinned.ts
- src/tauri/bindings.ts
- src/tauri/utils.ts
Added accelerators for some tray menu items to make them more aesthetic and practical.
- `'Settings'` uses the same shortcut(`CmdOrCtrl+,`) as the main window to bring up the settings page
- `'OCR'` and `'Show'` use the shortcuts configured in the settings, and they will update as the settings are updated; if not configured, they will be blank like `'Pin'`
- `'Hide'` and `'Quit'` use predefined shortcuts, which are enabled by default
| Before | After |
| -- | -- |
| ![image](https://github.com/openai-translator/openai-translator/assets/9566166/d67aaa59-4669-40f2-b78e-587578bb785d) | ![image](https://github.com/openai-translator/openai-translator/assets/9566166/956dc144-d3d6-4c3c-b73b-918dd9eba4ae) |
> feat: add accelerators for some tray menu items

- src-tauri/src/main.rs
Relate PRs https://github.com/openai-translator/openai-translator/pull/1474 https://github.com/openai-translator/openai-translator/pull/1524
After #1524, the window can only be reopened from the tray on macOS and not by clicking the dock bar.
> fix: reopen window

- src/common/hooks/useMemoWindow.ts
- src/tauri/windows/TranslatorWindow.tsx
> fix: do not show the translator window if the app runs at startup

- src/common/engines/claude.ts
Add `anthropic-dangerous-direct-browser-access` header refer to claude doc.
Issue: https://github.com/openai-translator/openai-translator/issues/1685
> Fix bug: CORS request error on Claude model

- vite.config.chromium.ts
I can't use the mouse to select text or open extensions in the right-click menu after my browser upgrades version because some problems occurred after the browser was upgraded to version 130. When the `use_dynamic_url` is set to true, the script fails to load.
related issue: 
https://github.com/samrum/vite-plugin-web-extension/issues/144
https://github.com/crxjs/chrome-extension-tools/issues/918
> feat: fix #1649. Repair the problem of browser extension scripts not load in Chrome and Edge due to CSP restrictions
