public/manifest.json

添加 `all_frames` 以支持在 iframe 中触发
ref: https://developer.chrome.com/docs/extensions/mv3/content_scripts/#frames
close #3

iframe support

---

src/content_script/PopupCard.tsx

fix: should only allow vertical textarea resize

---

src/content_script/translate.ts

I'm not really good at JavaScript, so I chose not to change any part of the code to avoid any errors. I hope someone could help finish it.

Add prompt for chinese traditional

---

src/background/index.ts

this pr add tts(text-to-speech) support to firefox using [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API)

feat: add tts support to firefox

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml

Copy from https://github.com/tisonkun/flink-cdc-connectors/issues/new/choose

chore: add issue form templates

---

README-CN.md

close #134
see: https://github.com/wey-gu/openai-translator/tree/i18n-readme
Banner:

feat: i18n of readme and some polishing

---

src/background/index.ts

I forgot to remove `detectLang` in the last pr.

chore(tts): remove unused import

---

src/content_script/PopupCard.tsx
src/content_script/translate.ts
src/popup/Settings.tsx

Add Grammar Analysis Mode #93 , feel free to close/decline if it's not appropriate.

Add Grammar Analysis Mode #93

---

src/content_script/PopupCard.tsx
src/content_script/index.tsx

fix: Add overflow check

---

src/tauri/App.tsx

refactor: Remove title bar for linux

---

package.json
src/content_script/PopupCard.tsx
yarn.lock

feat: upload image to translation with OCR

---

LICENSE
README-CN.md
README.md

fix: LICENSE

---

src/content_script/PopupCard.tsx

feat: add filtering function to the language switch drop-down list (#207)

---

package.json

fix: missing dependencies

---

README-CN.md
README.md
src-tauri/Cargo.toml
src-tauri/src/tray.rs
src-tauri/tauri.conf.json
src/content_script/PopupCard.tsx

feat & bugfix: pin, drag and drop with OCR

---

package.json
src/background/index.ts
src/content_script/utils.ts
src/popup/Settings.tsx
yarn.lock

this pr fixed two issues:
1. fixes #77 #206 
2. currently, firefox extension is broken because
replace lodash with underscore will solve this.

fix(browser): move fetch to background

---

src/components/SpeakerMotion.tsx
src/content_script/PopupCard.tsx

https://user-images.githubusercontent.com/18044730/224749496-a587411d-06cd-4153-ba0e-b35583b7c160.mov

feat: create speaker motion

---

src/content_script/PopupCard.tsx
src/content_script/translate.ts
src/tauri/App.tsx

Feature:
Add pin button to set window always on top, and indicates whether the window is at the top.
In addition, the state of 'always on top' is synchronized with the track menu.
Issue: https://github.com/yetone/openai-translator/issues/240

feat: add pin button

---

src/content_script/utils.ts

currently, translating animation is broken, this will fix that.

fix: translating animation

---

src/background/index.ts

Only one port should be allowed per tab

fix: only one port is allowed per tab

---

src/background/index.ts

fix: handle errors while reading a stream

---

src/common/utils.ts
src/content_script/PopupCard.tsx
src/popup/Settings.tsx
src/tauri/index.html

Add Dark theme support, auto switch by OS settings.
Color base on `baseui` theme.

Dark Mode Support

---

src/background/index.ts
src/content_script/PopupCard.tsx
src/content_script/utils.ts
src/popup/index.tsx

feat: allow use in popup

---

src/content_script/PopupCard.tsx
src/popup/Settings.tsx
src/tauri/App.tsx
src/tauri/utils.ts

1. add clearHotkey button
2. unregister hotkey before bind 
#297

feat: add clearHotkey

---

.github/workflows/release.yaml
.gitignore
Makefile
build.mjs
public/userscript.js

fix userscript style and create userscript build
[release for test](https://github.com/maltoze/openai-translator/releases/tag/untagged-4625dde6696535a377d7)

fix(userscript): import css file

---

src/background/index.ts
src/common/tts.ts
src/content_script/PopupCard.tsx
src/content_script/index.tsx

this pr removed tts from the background and using [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) for a more unified approach.
can download from [here](https://github.com/maltoze/openai-translator/releases/tag/untagged-3448bd949692cde2a9e1) to test.
close #278

feat: add tts support to desktop

---

README-CN.md
README.md

Add [Install via Scoop](https://github.com/ScoopInstaller/Extras/pull/10708)

chore: update readme

---

src/content_script/PopupCard.tsx

The popup card follows pointer when scrolling

Feat scroll move

---

src/content_script/PopupCard.tsx

the tooltip offset problem that appeared left

fix: Fix the offset problem when arrow to right by setting placement

---

src-tauri/tauri.conf.json
src/common/hooks/useMemoWindow.ts
src/content_script/PopupCard.tsx
src/popup/Settings.tsx
src/tauri/App.tsx
src/tauri/index.html

1.  Fixed header and footer
2.  Limit scroll area and style adjustment
3.  wrap hook to memorize window  properties

modified sth about action  and adaption of window

---

src/common/tts.ts

tts does not work well on mac unless `voice` is specified.

fix: mapping language tag and specify voice

---

README-CN.md
README.md

更新readme，补充Apple Silicon设备上提示文件损坏的说明

---

src/content_script/PopupCard.tsx

https://github.com/yetone/openai-translator/issues/384

feat: copy text without any style

---

src/common/types.ts
src/common/utils.ts
src/content_script/translate.ts
src/i18n/locales/en/translation.json
src/i18n/locales/ja/translation.json
src/i18n/locales/th/translation.json
src/i18n/locales/zh-Hans/translation.json
src/i18n/locales/zh-Hant/translation.json
src/popup/Settings.tsx

feat: GPT-4

---

src-tauri/tauri.conf.json
src/content_script/PopupCard.tsx
src/popup/Settings.tsx

the style callback is not valid in `@media`

fix desktop window style 

---

package.json
src/popup/Settings.tsx
tsconfig.json

It is necessary to config the version number before building app. Using scripts  is considered，todo+1

show version

---

src/content_script/PopupCard.tsx
src/i18n/locales/en/translation.json
src/i18n/locales/ja/translation.json
src/i18n/locales/th/translation.json
src/i18n/locales/zh-Hans/translation.json
src/i18n/locales/zh-Hant/translation.json

when finished_reason is 'length',users does not want to  clear the current translation and only display the Error instead

charactors limited

---

src/content_script/PopupCard.tsx

feat: add retry button for error message

---

src-tauri/build.rs
src-tauri/src/hotkey.rs
src-tauri/src/main.rs
src-tauri/src/ocr.rs
src-tauri/src/tray.rs
src-tauri/src/utils.rs
src-tauri/src/windows.rs

Make 'cargo fmt' and 'cargo clippy' happy

chore: cargo format and clippy

---

dist/userscript/index.css
public/userscript.js
src/content_script/PopupCard.tsx
src/options/index.tsx
src/popup/Settings.tsx

fix: make userscript works

---

src/content_script/PopupCard.tsx
src/i18n/locales/en/translation.json
src/i18n/locales/ja/translation.json
src/i18n/locales/th/translation.json
src/i18n/locales/zh-Hans/translation.json
src/i18n/locales/zh-Hant/translation.json

Issues: 
https://github.com/yetone/openai-translator/issues/463 
https://github.com/yetone/openai-translator/issues/150

feat: add clear input button

---

src/content_script/PopupCard.tsx

feat: autofocus input when activate pop card

---

src/common/tts.ts
src/content_script/PopupCard.tsx
src/popup/Settings.tsx

`speechSynthesis` may be undefined on Ubuntu.
fix #474
fix #446 
#451 
~don't know what's this~
```
Error: permission denied for this operation, plese try as super user
Thumb window does not exist
```

fix: check if speechSynthesis is undefined

---

.github/workflows/release.yaml
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json

- [Updater](https://tauri.app/v1/guides/distribution/updater/#docusaurus_skipToContent_fallback)
- https://github.com/tauri-apps/tauri-action/pull/287

feat: enable auto updating for users

---

src-tauri/src/utils.rs

完善Windows的剪切板回写方式，添加了剪切板内容是图片时的处理方法。

fix: Improve rewrite of windows clipboard

---

package.json
public/manifest.firefox.json
public/manifest.json
src/common/tts/edge-tts.ts
src/common/tts/index.ts
src/common/tts/types.ts
src/common/types.ts
src/common/utils.ts
src/content_script/PopupCard.tsx
src/popup/Settings.tsx
yarn.lock

This PR adds support for Edge TTS, allowing users to use the Microsoft Edge's online text-to-speech service without the need for an API key.
thanks https://github.com/rany2/edge-tts

feat: add support for Edge TTS

---

src/common/components/Settings.tsx
src/common/tts/edge-tts.ts
src/common/tts/index.ts
src/common/types.ts

feat: add rate and volume settings to tts

---

src-tauri/tauri.conf.json

fixes #723 
not familiar with tauri, but this works.

fix: saving not work on ubuntu

---

src/common/utils.ts

fix: can not open popup and options page

---

.eslintignore
.eslintrc.js
tsconfig.json
vite.config.chromium.ts
vite.config.firefox.ts
vite.config.tauri.ts

chore: resolve eslint complaints in the codebase

---

src/common/hooks/useSettings.ts

Fix the issue with the `setSettings` not working properly.

fix: useSettings hook not working properly

---

e2e/common.ts
e2e/hotkey.spec.ts
e2e/index.spec.ts
src/common/components/Settings.tsx

test: add hotkey e2e test

---

src/common/components/Settings.tsx
src/common/translate.ts

feat: support new models

---

src/browser-extension/background/index.ts

fix: query correct active tab

---

src/browser-extension/content_script/utils.ts

fix: incorrect positioning on certain pages

---

src/common/components/lang/data.ts
src/common/components/lang/lang.ts
src/common/tts/index.ts

- Svenska translation as target and origin
- Svenska TTS

feat: Svenska Support

---

src/browser-extension/content_script/index.tsx

fix: support firefox

---

src/common/translate.ts

fix: cannot destructure property finish details error

---

README-CN.md
README.md

`Star History Chart` supports dark theme.

`Star History Chart` supports dark theme.

---

src/common/components/CopyButton.tsx

`Toaster` has been added here 
https://github.com/openai-translator/openai-translator/blob/ae9f80d41970fe48a77019c460e13f4e9862a2db/src/common/components/Translator.tsx#L1956

fix: remove duplicate Toaster

---

package.json
pnpm-lock.yaml
src/browser-extension/content_script/index.tsx
src/common/components/Translator.tsx
src/common/store.ts

**BEFORE:**
https://github.com/openai-translator/openai-translator/assets/18044730/3f4a2a37-e8d8-476d-9262-76141534f7a7
----
**AFTER:**
https://github.com/openai-translator/openai-translator/assets/18044730/84a17ec4-153e-46fd-ad2f-71377ebb4086

feat(browser-extension): prevent position update if pinned and dragged

---

src/browser-extension/content_script/InnerContainer.tsx
src/browser-extension/content_script/index.tsx
src/common/components/Settings.tsx
src/common/utils.ts
vite.config.userscript.ts

fix: support userscript

---

src/browser-extension/background/index.ts
src/common/background/fetch.ts
src/common/components/Translator.tsx

close #931
close #794 
[scrnli_2023_8_8 11-55-02.webm](https://github.com/openai-translator/openai-translator/assets/18044730/b8b893e0-2527-4327-9005-bbca98aac385)

feat: add support for stopping generation

---

src/common/components/Settings.tsx
src/common/tts/index.ts

feat: allow custom voice variants

---

src/browser-extension/manifest.ts
src/browser-extension/options/index.tsx

**BEFORE:**
[scrnli_2023_9_6 18-07-19.webm](https://github.com/openai-translator/openai-translator/assets/18044730/954085fd-a735-4a64-9a51-3f5be462df16)
----
**AFTER:**
[scrnli_2023_9_6 18-07-57.webm](https://github.com/openai-translator/openai-translator/assets/18044730/4d229186-9c6f-4b92-9793-f62fec0f4bf7)

fix(browser-extension): open options ui in new tab

---

pnpm-lock.yaml
src-tauri/Cargo.lock
src-tauri/src/config.rs
src-tauri/src/hotkey.rs
src-tauri/src/main.rs
src-tauri/src/utils.rs
src-tauri/src/writing.rs
src/common/components/Settings.tsx
src/common/components/Translator.tsx
src/common/i18n/locales/en/translation.json
src/common/i18n/locales/ja/translation.json
src/common/i18n/locales/th/translation.json
src/common/i18n/locales/zh-Hans/translation.json
src/common/i18n/locales/zh-Hant/translation.json
src/common/translate.ts
src/common/types.ts
src/common/utils.ts
src/tauri/App.tsx
src/tauri/utils.ts

https://github.com/openai-translator/openai-translator/assets/1206493/89897646-8e4f-466a-ae73-14126b8a9892

feat: writing

---

src/common/translate.ts

feat: provide phonetic notation for selected word

---

src/browser-extension/content_script/index.tsx
src/common/user-event.ts

**I selected the content, icon will appear, but when I click in other area like image, video, icon still there**  👇
**The same problem in YouTube video**  👇

Hide icon based on the node type of the caret

---

package.json
pnpm-lock.yaml
src-tauri/src/config.rs
src-tauri/src/main.rs
src-tauri/src/tray.rs
src-tauri/src/windows.rs
src-tauri/tauri.conf.json
src/common/analysis.ts
src/common/components/Settings.tsx
src/common/components/Translator.tsx
src/common/hooks/useMemoWindow.ts
src/common/i18n/locales/en/translation.json
src/common/i18n/locales/ja/translation.json
src/common/i18n/locales/th/translation.json
src/common/i18n/locales/zh-Hans/translation.json
src/common/i18n/locales/zh-Hant/translation.json
src/common/types.ts
src/common/utils.ts
src/tauri/App.tsx
src/tauri/Window.tsx
src/tauri/action_manager.html
src/tauri/index.html
src/tauri/settings.html
src/tauri/settings.tsx
src/tauri/updater.html

fix https://github.com/openai-translator/openai-translator/issues/1106

fix: ipc cors in windows

---

src/common/engines/abstract-openai.ts

chore: do not clear the result if the result is actully ok (got [DONE])
below is the gif to show the issue:

chore: do not clear the result if the result is actully ok (got [DONE])

---

src/common/components/Translator.tsx

修正不正確的錯誤訊息

---

src-tauri/src/main.rs
src-tauri/src/windows.rs

See code comments for more details.
- fix https://github.com/openai-translator/openai-translator/issues/1185
- fix https://github.com/openai-translator/openai-translator/issues/1096
- fix https://github.com/openai-translator/openai-translator/issues/889
- fix https://github.com/openai-translator/openai-translator/issues/696
- fix https://github.com/openai-translator/openai-translator/issues/564
- fix https://github.com/openai-translator/openai-translator/issues/434
- fix https://github.com/openai-translator/openai-translator/issues/383

fix: Fix build on linux platform

---

.github/workflows/release.yaml

We are not ready for tauri beta yet.

ci: Fix release workflow

---

package.json
pnpm-lock.yaml

fix #1276
Tested on chromium extension.

chore: Update js-tiktoken to 1.0.10 (#1276)

---

src/common/components/Translator.tsx
src/common/engines/abstract-openai.ts
src/common/engines/claude.ts
src/common/engines/gemini.ts
src/common/lang/index.ts
src/common/translate.ts

fix: Revert "optimize: refine prompts (#1358)"

---

src/common/components/Settings.tsx
src/common/engines/gemini.ts
src/common/types.ts
src/common/utils.ts

feat: add gemini api url settings

---

src/common/components/Translator.tsx

close https://github.com/openai-translator/openai-translator/issues/1432

fix: clear translated content when clearing input in translator

---

src/common/components/NumberInput.tsx
src/common/components/Settings.tsx
src/common/components/Translator.tsx
src/common/i18n/locales/en/translation.json
src/common/i18n/locales/ja/translation.json
src/common/i18n/locales/th/translation.json
src/common/i18n/locales/tr/translation.json
src/common/i18n/locales/zh-Hans/translation.json
src/common/i18n/locales/zh-Hant/translation.json
src/common/types.ts
src/common/utils.ts

https://github.com/openai-translator/openai-translator/issues/1445

feat: support change font size

---

src/common/components/Settings.tsx
src/common/engines/abstract-openai.ts
src/common/engines/azure.ts
src/common/types.ts
src/common/utils.ts

fix: azure support set max_tokens

---

src-tauri/gen/schemas/linux-schema.json

tauri: Fix linux schema is missing

---

src/common/services/promotion.ts

Just for test, please don't merge.

fix: Skip promotion content if fetch failed

---

src/common/components/Translator.tsx
src/common/components/Vocabulary.tsx

https://github.com/openai-translator/openai-translator/issues/1430

feat: vocabulary pronunciation

---

.eslintrc.js
package.json
pnpm-lock.yaml
src/common/engines/chatgpt.ts

I fixed the issue with chatgpt-web, but it seems there's something wrong with ESLint when I try to commit. Please check it out.

fix: chatgpt-web

---

package.json
pnpm-lock.yaml
src/common/components/Translator.tsx
src/common/store/setting.ts
src/tauri/components/Window.tsx

Support using shortcut keys to invoke settings on the desktop.
- macOS: `command` + `,`
- Windows : `Crtl` + `,`
https://github.com/openai-translator/openai-translator/assets/33956589/294a4bec-b989-488c-8a8d-3f705e0f50f8

feat: support using shortcut keys to invoke settings on the desktop

---

src/browser-extension/manifest.ts
src/common/assets/images/cohere.svg
src/common/components/Settings.tsx
src/common/components/icons/CohereIcon.tsx
src/common/engines/cohere.ts
src/common/engines/gemini.ts
src/common/engines/index.ts
src/common/types.ts
src/common/utils.ts

https://github.com/openai-translator/openai-translator/issues/1508

feat: support cohere

---

src/common/components/DurationPicker.tsx
src/common/components/Settings.tsx
src/common/engines/ollama.ts
src/common/i18n/locales/en/translation.json
src/common/i18n/locales/ja/translation.json
src/common/i18n/locales/th/translation.json
src/common/i18n/locales/tr/translation.json
src/common/i18n/locales/zh-Hans/translation.json
src/common/i18n/locales/zh-Hant/translation.json
src/common/types.ts
src/common/utils.ts

https://github.com/openai-translator/openai-translator/issues/1536

feat: ollama keep alive

---

.github/workflows/release.yaml

ref #1361
Upload firefox extension while releasing new versions.
[Preview manifests](https://github.com/iosmanthus/openai-translator/releases/tag/untagged-75d8919b3bd2056c6c55)

release firefox extension

---

src-tauri/src/main.rs

fix: reopen only available on macos

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

fuck tauri!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1

fix: lock tauri version

---

src/common/engines/abstract-openai.ts

close https://github.com/openai-translator/openai-translator/issues/1664

fix: close https://github.com/openai-translator/openai-translator/issues/1664
